import { DateTime } from '@airtasker/spot';

export type GetMyPollByIdResponse = {
  /**
   * The unique identifier of the poll.
   */
  id: string;
  
  /**
   * The poll description.
   */
  description: string;
  
  /**
   * The user prompt for AI generation.
   */
  userPrompt: string | null;
  
  /**
   * The questions for the poll.
   */
  questions: {
    /**
     * The unique identifier of the question.
     */
    id: string;
    
    /**
     * The type of question.
     */
    type: 'MULTIPLE_CHOICE' | 'SINGLE_CHOICE' | 'RATING' | 'TEXT';
    
    /**
     * The question's text/label, visible to the user.
     */
    title: string;
    
    /**
     * Whether the question was generated by AI.
     */
    isAiGenerated: boolean;
    
    /**
     * Whether multiple responses are allowed for this question.
     */
    multipleResponses: boolean;
    
    /**
     * Whether the user has responded to this question.
     */
    isResponded: boolean;
    
    /**
     * The poll options related to the question.
     */
    pollOptions: {
      /**
       * The unique identifier of the option.
       */
      id: string;
      
      /**
       * The option's text/label, visible to the user.
       */
      title: string;
      
      /**
       * The display order of the option.
       */
      displayOrder: number;
      
      /**
       * Whether this option is selected by the user.
       */
      isSelected: boolean;
    }[];
    
    /**
     * Whether the question was suggested by AI.
     */
    isAiSuggested: boolean;
  }[];
  
  /**
   * The audience IDs that can participate in the poll.
   */
  audienceIds: string[];
  
  /**
   * The type of poll.
   */
  type: 'ANONYMOUS' | 'CONFIDENTIAL';
  
  /**
   * The poll settings.
   */
  settings: {
    /**
     * Whether the poll responses are anonymous.
     */
    isAnonymous: boolean;
    
    /**
     * Whether results are allowed to be shown.
     */
    allowResults: boolean;
    
    /**
     * Whether results can be shown before the user responds.
     */
    allowResultsBeforeResponse: boolean;
    
    /**
     * When the poll starts.
     */
    startsAt: DateTime;
    
    /**
     * When the poll ends.
     */
    endsAt: DateTime;
  };
  
  /**
   * Whether the poll was generated by AI.
   */
  isAiGenerated: boolean;
  
  /**
   * The delivery type of the poll.
   */
  deliveryType: 'IMMEDIATE' | 'SCHEDULED';
  
  /**
   * The current state of the poll.
   */
  state: 'DRAFT' | 'ACTIVE' | 'CLOSED' | 'DELETED' | 'EXPIRED';
  
  /**
   * Information about the poll creator.
   */
  createdBy: {
    /**
     * The unique identifier of the creator.
     */
    id: string;
    
    /**
     * The creator's full name.
     */
    name: string;
    
    /**
     * The creator's email address.
     */
    email: string;
  };
  
  /**
   * When the poll was created.
   */
  createdAt: DateTime;
  
  /**
   * When the poll was last updated.
   */
  updatedAt: DateTime;
};
